apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  creationTimestamp: null
  name: codecommit-creds
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Sir-gits-a-lot/crossplane-demo
  username: utkarshmishra@tataelxsi.co.in+1-at-084726943794
  password: JaDdZ2DiP0vi9AD3CHlO2TEp0jChcuLp/Xs4LM1cDW8=